[package]
name = "vampus"
version = "0.4.3"
description = "A CLI tool for automated semantic version management across configurable file patterns."
license = "MIT"
repository = "https://github.com/atareao/vampus"
edition = "2024"

[dependencies]
clap = { version = "4.5.51", features = ["derive"] }
clap_complete = "4.5"
regex = "1.12.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_yaml = "0.9.34"
thiserror = "2"
tokio = { version = "1.48.0", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }